import Foundation
import Testing
@testable import RAKit

/// Decodes the golden frames generated by the Go server (protocol/fixtures).
struct FixtureTests {
    static let dir = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent().appending(path: "../../../../protocol/fixtures").standardized

    func load(_ name: String) throws -> Data {
        try Data(contentsOf: Self.dir.appending(path: name))
    }

    struct Notification<P: Decodable>: Decodable { var method: String; var params: P }
    struct EventsParams: Decodable { var stream: String; var events: [Event] }
    struct Response<R: Decodable>: Decodable { var id: JSONValue; var result: R?; var error: RPCError? }

    @Test func sessionEvents() throws {
        let n = try WireCoding.decoder().decode(Notification<EventsParams>.self, from: load("notification_events_session.json"))
        #expect(n.method == "events")
        #expect(n.params.events.count == 14)
        let session = try #require(n.params.events[0].session)
        #expect(session.status == .awaitingApproval)
        #expect(session.workspace.kind == .worktree)
        let turn = try #require(n.params.events[1].turn)
        #expect(turn.usage?.costUsd == 0.0123)
        let items = n.params.events.compactMap(\.item)
        #expect(items.count == 11)
        #expect(items.map(\.kind) == [.userMessage, .reasoning, .toolCall, .assistantMessage, .approval, .approval, .approval, .plan, .notice, .error, .assistantMessage])
        #expect(items[0].images?.first?.mimeType == "image/png")
        #expect(items[0].images?.first?.aspectRatio == 1170.0 / 2532.0)
        #expect(items[2].images?.first?.width == nil)  // WebP: no dimensions
        #expect(items[2].images?.first?.aspectRatio == nil)
        #expect(items[2].tool?.input?["command"]?.stringValue == "go test ./...")
        #expect(items[2].tool?.exitCode == 0)
        #expect(items[4].approval?.options.map(\.kind) == [.allowOnce, .allowSession, .deny])
        #expect(items[5].approval?.special == .question)
        #expect(items[5].approval?.decision?.answers?["Which DB?"] == "SQLite")
        #expect(items[6].approval?.special == .plan)
        #expect(items[7].plan?.entries?.count == 2)
        #expect(items[10].parentItemId == "i3")
        // Unknown event types decode without payload instead of failing the batch.
        #expect(n.params.events.last?.type == "future.event")
    }

    @Test func indexEvents() throws {
        let n = try WireCoding.decoder().decode(Notification<EventsParams>.self, from: load("notification_events_index.json"))
        #expect(n.params.events.map(\.type) == ["project.upserted", "session.upserted", "project.removed"])
        #expect(n.params.events[0].project?.isGitRepo == true)
        #expect(n.params.events[2].id == "p0")
    }

    @Test func responses() throws {
        let dec = WireCoding.decoder()
        struct Harnesses: Decodable { var harnesses: [HarnessInfo] }
        let h = try dec.decode(Response<Harnesses>.self, from: load("response_harness_list.json"))
        #expect(h.result?.harnesses.count == 2)
        #expect(h.result?.harnesses[0].usable == true)
        #expect(h.result?.harnesses[1].usable == false)
        #expect(h.result?.harnesses[1].hint?.isEmpty == false)
        // A model's own efforts replace the harness's; others get the default model's.
        let claude = h.result?.harnesses[0]
        #expect(claude?.efforts(forModel: "sonnet").map(\.id) == ["low", "high"])
        #expect(claude?.efforts(forModel: nil).map(\.id) == ["low", "medium", "high"])
        #expect(h.result?.harnesses[1].efforts(forModel: nil).isEmpty == true)

        let d = try dec.decode(Response<Diff>.self, from: load("response_diff.json"))
        #expect(d.result?.files.map(\.status) == [.modified, .renamed, .added])
        #expect(d.result?.files[2].binary == true)

        let fs = try dec.decode(Response<FSListing>.self, from: load("response_fs_list.json"))
        #expect(fs.result?.entries.count == 2)

        let e = try dec.decode(Response<Empty>.self, from: load("response_error.json"))
        #expect(e.error?.code == "conflict")

        let s = try dec.decode(Response<Session>.self, from: load("response_session.json"))
        #expect(s.result?.title == "Fix the tests")
        #expect(s.result?.context?.fraction == 0.26)
        #expect(s.result?.modelName(in: nil) == "Sonnet 5.5")
        #expect(s.result?.modelInfo?.effort == "high")
        #expect(s.result?.effort == "high")

        let p = try dec.decode(PairResult.self, from: load("http_pair_response.json"))
        #expect(p.token == "0123abcd")
    }
}
