// Reads the golden frames generated by the Go server (protocol/fixtures), as
// apple/RAKit/Tests/RAKitTests/FixtureTests.swift does.
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
  aspectRatio,
  contextFraction,
  effortsForModel,
  imageIdLinkedBy,
  modelName,
  parseDate,
  usable,
  type Diff,
  type Event,
  type FSListing,
  type HarnessInfo,
  type PairResult,
  type Session,
} from "./models";

const dir = join(import.meta.dirname, "../../../protocol/fixtures");
const load = (name: string) => JSON.parse(readFileSync(join(dir, name), "utf8"));

describe("fixtures", () => {
  it("session events", () => {
    const n = load("notification_events_session.json");
    expect(n.method).toBe("events");
    const events: Event[] = n.params.events;
    expect(events).toHaveLength(14);
    const session = events[0].session!;
    expect(session.status).toBe("awaiting_approval");
    expect(session.workspace.kind).toBe("worktree");
    expect(events[1].turn?.usage?.costUsd).toBe(0.0123);
    const items = events.flatMap((e) => (e.item ? [e.item] : []));
    expect(items).toHaveLength(11);
    expect(items.map((i) => i.kind)).toEqual([
      "user_message",
      "reasoning",
      "tool_call",
      "assistant_message",
      "approval",
      "approval",
      "approval",
      "plan",
      "notice",
      "error",
      "assistant_message",
    ]);
    expect(items[0].images?.[0].mimeType).toBe("image/png");
    expect(aspectRatio(items[0].images![0])).toBe(1170 / 2532);
    expect(items[2].images?.[0].width).toBeUndefined(); // WebP: no dimensions
    expect(aspectRatio(items[2].images![0])).toBeUndefined();
    expect((items[2].tool?.input as Record<string, unknown>).command).toBe("go test ./...");
    expect(items[2].tool?.exitCode).toBe(0);
    // A reply links to the images it shows as rad-image:<id>.
    const shown = items[3].images![0];
    expect(items[3].text?.endsWith(`![Screenshot](rad-image:${shown.id})`)).toBe(true);
    expect(imageIdLinkedBy(`rad-image:${shown.id}`)).toBe(shown.id);
    expect(imageIdLinkedBy("https://example.com/a.png")).toBeUndefined();
    expect(items[4].approval?.options?.map((o) => o.kind)).toEqual(["allow_once", "allow_session", "deny"]);
    expect(items[5].approval?.special).toBe("question");
    expect(items[5].approval?.decision?.answers?.["Which DB?"]).toBe("SQLite");
    expect(items[6].approval?.special).toBe("plan");
    expect(items[7].plan?.entries).toHaveLength(2);
    expect(items[10].parentItemId).toBe("i3");
    // Unknown event types come through, for the stores to skip.
    expect(events[events.length - 1].type).toBe("future.event");
    expect(Number.isNaN(parseDate(items[0].createdAt))).toBe(false);
  });

  it("index events", () => {
    const events: Event[] = load("notification_events_index.json").params.events;
    expect(events.map((e) => e.type)).toEqual(["project.upserted", "session.upserted", "project.removed"]);
    expect(events[0].project?.isGitRepo).toBe(true);
    expect(events[2].id).toBe("p0");
  });

  it("responses", () => {
    const harnesses: HarnessInfo[] = load("response_harness_list.json").result.harnesses;
    expect(harnesses).toHaveLength(2);
    expect(usable(harnesses[0])).toBe(true);
    expect(usable(harnesses[1])).toBe(false);
    expect(harnesses[1].hint).toBeTruthy();
    // A model's own efforts replace the harness's; others get the default model's.
    const claude = harnesses[0];
    expect(effortsForModel(claude, "sonnet").map((e) => e.id)).toEqual(["low", "high"]);
    expect(effortsForModel(claude, undefined).map((e) => e.id)).toEqual(["low", "medium", "high"]);
    expect(effortsForModel(harnesses[1], undefined)).toEqual([]);
    expect(claude.commands?.map((c) => "/" + c.name)).toEqual(["/compact"]);
    expect(claude.commands?.[0].description).toBeTruthy();
    expect(harnesses[1].commands).toBeUndefined();

    const diff: Diff = load("response_diff.json").result;
    expect(diff.files.map((f) => f.status)).toEqual(["modified", "renamed", "added"]);
    expect(diff.files[2].binary).toBe(true);

    const fs: FSListing = load("response_fs_list.json").result;
    expect(fs.entries).toHaveLength(2);

    expect(load("response_error.json").error.code).toBe("conflict");

    const s: Session = load("response_session.json").result;
    expect(s.title).toBe("Fix the tests");
    expect(contextFraction(s.context)).toBe(0.26);
    expect(modelName(s, undefined)).toBe("Sonnet 5.5");
    expect(s.modelInfo?.effort).toBe("high");
    expect(s.effort).toBe("high");

    const p: PairResult = load("http_pair_response.json");
    expect(p.token).toBe("0123abcd");
  });

  it("notifications", () => {
    expect(load("notification_synchronized.json").params).toEqual({ stream: "session:s1", seq: 14, reset: true });
    expect(load("notification_resync.json").params.stream).toBe("session:s1");
    expect(load("response_subscribe.json").result).toEqual({ stream: "session:s1", seq: 14 });
  });
});

describe("parseDate", () => {
  it("reads Go's times", () => {
    expect(parseDate("2026-10-09T01:50:59.955123456Z")).toBe(Date.UTC(2026, 9, 9, 1, 50, 59, 955));
    expect(parseDate("2026-10-09T01:50:59Z")).toBe(Date.UTC(2026, 9, 9, 1, 50, 59));
    expect(parseDate("2026-10-09T01:50:59.9+02:00")).toBe(Date.UTC(2026, 9, 8, 23, 50, 59, 900));
  });
});
